package co.iostream.apps.android.io_private.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xffe06070)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0x1a7C7768)
val md_theme_light_onPrimaryContainer = Color(0xFF211B00)
val md_theme_light_secondary = Color(0xd42196F3)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xffffffff)
val md_theme_light_onSecondaryContainer = Color(0xFF22005D)
val md_theme_light_tertiary = Color(0xd44CAF50)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0x4aFFD6FC)
val md_theme_light_onTertiaryContainer = Color(0xFF36003E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B16)
val md_theme_light_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4739)
val md_theme_light_outline = Color(0xFF79757F)
val md_theme_light_inverseOnSurface = Color(0xFFF6F0E7)
val md_theme_light_inverseSurface = Color(0xFF32302A)
val md_theme_light_inversePrimary = Color(0xFFE0C645)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6E5E00)
val md_theme_light_outlineVariant = Color(0xFFCDC6B4)
val md_theme_light_scrim = Color(0xaaffffff)

val md_theme_dark_primary = Color(0xffe06070)
val md_theme_dark_onPrimary = Color(0xFF393000)
val md_theme_dark_primaryContainer = Color(0x11ffffff)
val md_theme_dark_onPrimaryContainer = Color(0xFFFEE25E)
val md_theme_dark_secondary = Color(0x442196F3)
val md_theme_dark_onSecondary = Color(0xFF3A0092)
val md_theme_dark_secondaryContainer = Color(0x40ffffff)
val md_theme_dark_onSecondaryContainer = Color(0xFFE9DDFF)
val md_theme_dark_tertiary = Color(0x4a4CAF50)
val md_theme_dark_onTertiary = Color(0xFF580064)
val md_theme_dark_tertiaryContainer = Color(0x227C058B)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6FC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B16)
val md_theme_dark_onBackground = Color(0xFFE7E2D9)
val md_theme_dark_surface = Color(0xFF1D1B16)
val md_theme_dark_onSurface = Color(0xFFE7E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4B4739)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC6B4)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B16)
val md_theme_dark_inverseSurface = Color(0xFFE7E2D9)
val md_theme_dark_inversePrimary = Color(0xFF6E5E00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE0C645)
val md_theme_dark_outlineVariant = Color(0xFF4B4739)
val md_theme_dark_scrim = Color(0xaa000000)

val Theme = Color(0xffe06070)
val ThemeLighter = Color(0xfff07080)
val ThemeDarker = Color(0xffd05060)
val ThemeDarkest = Color(0xff221100)
val Foreground = Color(0xffffffff)
val Foreground2 = Color(0xffaaaaaa)
val Border = Color(0x20ffffff)
val ButtonColor = Color(0x33d7dadd)
val ButtonColor2 = Color(0x227a8793)
val ButtonColor3 = Color(0xff23272b)

val WindowBackground = Color(0xff222222)
val PageBackground = Color(0xff191919)
val DockBackground = Color(0x20ffffff)
val PopupBackground = Color(0xff333333)

val seed = Color(0x1fee8800)